# Generated by Django 3.2.25 on 2024-03-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraftModel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iataCode', models.CharField(max_length=3)),
                ('airportName', models.CharField(max_length=100)),
                ('airportLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=100)),
                ('departureDate', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('seatsAvailableToBook', models.IntegerField()),
                ('airCraft', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departureAirport', to='Flight.aircraft')),
                ('departureAirport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='destinationAirport', to='Flight.airport')),
                ('destinationAirport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Flight.airport')),
            ],
        ),
    ]
