# Generated by Django 5.1.4 on 2024-12-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_flight_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled ', 'Scheduled '), ('Delayed ', 'Delayed '), ('Departed', 'Departed'), ('In Air', 'In Air'), ('Landed', 'Landed'), ('Arrived', 'Arrived'), ('Cancelled ', 'Cancelled '), ('Expected', 'Expected'), ('Past Flight', 'Past Flight'), ('Diverted', 'Diverted')], default='Scheduled', max_length=15)),
                ('flight', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Flight.flight')),
            ],
        ),
    ]
