# Generated by Django 3.2.25 on 2024-03-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('dateRegistered', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardsLevel', models.CharField(choices=[('BRONZE', 'Bronze'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('totalPoints', models.IntegerField()),
                ('memberDetails', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Member.member')),
            ],
        ),
    ]
