# Generated by Django 3.2.25 on 2024-03-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rewardsLevel',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LoyaltyProgram',
        ),
    ]
