# Generated by Django 3.2.25 on 2024-11-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0002_auto_20240327_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(max_length=10)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('dateRegistered', models.DateField()),
                ('rewardsLevel', models.CharField(choices=[('BRONZE', 'Bronze'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('totalPoints', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
