# Generated by Django 3.2.25 on 2024-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_alter_member_dateregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='dateRegistered',
            field=models.CharField(max_length=100),
        ),
    ]
