# Generated by Django 3.2.25 on 2024-11-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0008_alter_memberdetails_dateregistered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='dateRegistered',
        ),
    ]
