# Generated by Django 3.2.25 on 2024-03-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(choices=[('ROUNDTRIP', 'Round Trip'), ('ONEWAY', 'One way')], default='ROUNDTRIP', max_length=15)),
                ('departingFlight', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departingFlight', to='Flight.flight')),
            ],
        ),
    ]
