# Generated by Django 3.2.25 on 2024-03-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='departingFlight',
        ),
    ]
