# Generated by Django 3.2.25 on 2024-03-30 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
        ('Trip', '0002_remove_trip_departingflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departingFlight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departingFlight', to='Flight.flight'),
        ),
        migrations.AddField(
            model_name='trip',
            name='returningFlight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='returningFlight', to='Flight.flight'),
        ),
    ]
