# Generated by Django 3.2.25 on 2024-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='dob',
            field=models.DateField(max_length=100),
        ),
    ]
