# Generated by Django 3.2.25 on 2024-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0005_alter_passengers_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='dob',
            field=models.DateField(),
        ),
    ]
