# Generated by Django 3.2.25 on 2024-10-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0006_alter_passengers_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=16)),
                ('expiryMonth', models.CharField(max_length=2)),
                ('expiryYear', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
