# Generated by Django 6.0 on 2025-12-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0009_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isCheckedIn',
            field=models.BooleanField(default=False),
        ),
    ]
