# Generated by Django 6.0 on 2025-12-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0010_booking_ischeckedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carryOnQuantity', models.IntegerField()),
                ('checkedInQuantity', models.IntegerField()),
                ('specialBaggage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportNumber', models.CharField(max_length=16)),
                ('firstNameOnPassport', models.CharField(max_length=100)),
                ('lastNameOnPassport', models.CharField(max_length=100)),
                ('expiryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckInNumber', models.CharField(max_length=10)),
                ('seatSelection', models.CharField(max_length=10)),
                ('baggage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Trip.baggage')),
                ('passport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Trip.passport')),
            ],
        ),
    ]
