# Generated by Django 6.0 on 2025-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0011_baggage_passport_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='expiryDate',
            field=models.CharField(),
        ),
    ]
