# Generated by Django 6.0 on 2025-12-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0012_alter_passport_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Trip.booking'),
        ),
    ]
