# Generated by Django 6.0 on 2025-12-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0013_checkin_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='CheckInNumber',
            new_name='checkInNumber',
        ),
    ]
